echo " "
echo "--------------------------- I N I C I O ------------------------------------"
echo " "
echo "Comparando MD5..."
md5sum $1 $2
echo " "
echo " "
echo "----------------------------------------------------------------------------"
echo " "
echo "Comparando conteúdo..."
python3 compararConteudo.py $1 $2
echo " "
echo " "
echo "----------------------------------------------------------------------------"
echo " "
echo "Extraindo estatísticas 1..."
python3 estatisticasGenoma.py $1
echo " "
echo " "
echo "----------------------------------------------------------------------------"
echo " "
echo "Extraindo estatísticas 2..."
python3 estatisticasGenoma.py $2
echo " "
echo " "
echo "--------------------------- T E R M I N O ----------------------------------"
echo " "